### ISSUE TITLE
[New instance] Privacy is Good

### ISSUE THREAD

**Issue by PrivacyisGood** [MaximilianGT500/invidious-new-instances#1]
### URL

https://invidious.privacy.gd/

### Mandatory checks

- [X] Instance has a domain name
- [X] Instance is served over HTTPS
- [X] Statistics (`/api/v1/stats`) are enabled

### Maintainer chart

- [X] Ensure that my instance is up to date (less than one month old)
- [X] Ensure a proper uptime of my instance (around 90%)

### Host country

United States

### Analytics

- [ ] They are GDPR/CCPA compliant
- [ ] This is stated in your Privacy Policy
- [ ] You have provided the source code's URL in the dedicated field above

### Additionnal informations

Onion: http://2rorw2w54tr7jkasn53l5swbjnbvz3ubebhswscnc54yac6gmkxaeeqd.onion/

Thank you!

**Comment by MaximilianGT500** [comment]
Thanks, i add it to the Page i send you then the informations.

**Comment by MaximilianGT500** [comment]
Added to the Page.

URL: https://invidious.privacy.gd
.onion URL: http://2rorw2w54tr7jkasn53l5swbjnbvz3ubebhswscnc54yac6gmkxaeeqd.onion
Monitoring API: m790234726-014214a1dd363c80cc60c7b3

Thank you!
